config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homes#top"
  get 'home/about' => 'homes#about'
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:show, :index, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :title, presence:true, uniqueness: true, length: {minimum:2, maximum:20}
  validates :body, presence:true, length:{maximum:200}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book
    
    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  validates_uniqueness_of :book_id, scope: :user_id

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true, uniqueness: true, length: {minimum:2, maximum:20}
  validates :introduction, length: {maximum:50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
    
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  def top
  end
  
  def index
    @books = Book.all
    @book = Book.new
  end
  
  def create
    # １.&2. データを受け取り新規登録するためのインスタンス作成
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    #本を投稿した人→特定
    # 3. データをデータベースに保存するためのsaveメソッド実行
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end
  
  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    #ユーザー情報も取得
  end
  
  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def destroy
    book = Book.find(params[:id])  # データ（レコード）を1件取得
    book.destroy  # データ（レコード）を削除
    redirect_to books_path  # 投稿一覧画面へリダイレクト 
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] ="You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back fallback_location: root_path
    #:のあと→前の画面に戻れなかったらroot_pathに飛ぶ
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back fallback_location: root_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = current_user.post_comments.new(post_comment_params)
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user #1人選んでそれが自分だったときに
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end
  
  def index
    @users = User.all
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<div>
  <h1>User info</h1>
  <%= image_tag user.get_profile_image(100,100) %>
  
  <table class="table">
    <tr>
    <th>name</th>
    <th><%= user.name %></th>
    </tr>
    <th>introduction</th>
    <th><%= user.introduction %></th>
  </table>
  <%= link_to edit_user_path(user), class: 'btn btn-primary' do %>
  <i class="fas fa-user-cog"></i>
  <% end %>
</div>

<h1>New book</h1>
<!-- form_with部分 -->

<%= form_with model: Book.new do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_error.html.erb
<% if obj.errors.any? %>
  <h3><%= pluralize(obj.errors.count, "error") %> prohibited this book from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<%= form_with model: @book do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>
  <%= f.submit "Update Book" %>
  <%= link_to "Show", book_path(@book) %>
  <%= link_to "Back", books_path %>
  
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this object from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
<% end %>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
<div class="row" >
<div class="col-md-3">
<%= render 'book', user: current_user %>
<%= render 'error', obj: @book %>
</div>

<div class="col-md-8 offset-md-1" >
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th colspan="3"></th>
  </tr>

  <% @books.each do |book| %>
  <tr>
    <td><%= link_to(image_tag(book.user.get_profile_image(100,100)), user_path(book.user)) %></td>
    <td><%= link_to book.title, book_path(book) %></td>
    <td><%= book.body %></td>
<td>
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
    <i class="fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
    <i class="fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% end %>
</td>
<td>
  <p>コメント数: <%= @book.book_comments.count %></p>
</td>
  </tr>
  <% end %>

</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row" >
<div class="col-md-3">
<%= render 'book', user: @book.user %>
</div>

<div class="col-md-8 offset-md-1" >
<h3>Book detail</h3>
<table class="table table-hover table-inverse">
  <tbody>
    <tr>
      <td>
        <%= image_tag @book.user.get_profile_image(100,100) %><br>
        <%= link_to @book.user.name, user_path(@book.user) %>
      </td>
      <td><%= link_to @book.title, book_path(@book) %></td>
      <td><%= @book.body %></td>
      <td>
        <% if @book.favorited_by?(current_user) %>
        <p>
          <%= link_to book_favorites_path(@book), method: :delete do %>
          <i class="fa-heart" style="color: #62d7fe;"></i>
          <%= @book.favorites.count %>
          <% end %>
        </p>
        <% else %>
        <p>
          <%= link_to book_favorites_path(@book), method: :post do %>
          <i class="fa-heart" style="color: #62d7fe;"></i>
          <%= @book.favorites.count %>
          <% end %>
        </p>
        <% end %>
      </td>
      <td>
        <p>コメント数: <%= @book.book_comments.count %></p>
      </td>
      <% if @book.user == current_user %>
      <td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
      <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %></td>
      <% end %>
    </tr>
  </tbody>
  

</table>
<table>
  <tr>
    <td></td>
    <td></td>
    <td></td>
  </tr>
<% @book.book_comments.each do |book_comment| %>
<tr>
  <td><%= image_tag book_comment.user.get_profile_image(100,100) %><br>
  <%= book_comment.user.name %></td>
  <td><%= book_comment.comment %></td>
  <% if book_comment.user == current_user %>
    <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete %></td>
  <% end %>
</tr>
<% end %>
</table>

<%= form_with model:[@book,@book_comment] do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100" %>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>


</div>
</div>
</div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
<body>
    <header>
      <nav class= "navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class: "navbar-brand" do %>
          <span>Bookers</span>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="navbar-collapse collapse show" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user),class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>Home
                <% end %>
              </li>
              <li>
                <%= link_to users_path,class: 'nav-link text-light'  do %>
                <i class="fas fa-users"></i>Users
                <% end %>
              </li>
              <li>
                <%= link_to books_path,class: 'nav-link text-light'  do %>
                <i class="fas fa-book-open"></i>Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i>logout
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to root_path,class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>Home
                <% end %>
              </li>
              <li>
                <%= link_to home_about_path,class: 'nav-link text-light' do %>
                  <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i>sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i>login
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% flash.each do |key, value| %>
     <%= content_tag(:div, value, class: key) %>
    <% end %>
</body>


  <main>
    <%= yield %>
  </main>

<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>
</html>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_with model: @user do |f| %>
  <p>Name</p>
  <%= f.text_field :name %>
  <p>Image</p>
  <%= f.file_field :profile_image, placeholder: "ファイルを選択", accept: "image/*" %> 
  <p>Introduction</p>
  <%= f.text_area :introduction %>
  <%= f.submit "Update User" %>
  

<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this object from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0" >
<div class="row" >
<div class="col-md-3" >
<%= render 'books/book', user: current_user %>
</div>

<div class="col-md-8 offset-md-1" >

<h3>Users</h3>
<table class="table" >
  <tr>
  <th>image</th>
  <th>name</th>
  <th colspan="3"></th>
  </tr>
  
 
  <% @users.each do |user| %>
  <tr>
    <td><%= image_tag user.get_profile_image(100,100) %></td>
    <td><%= user.name %></td>
    <td><%= link_to "Show", user_path(user) %></td>
  
  </tr>
  <% end %>

</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0" >
<div class="row" >
<div class="col-md-3">
<%= render 'books/book', user: @user %>
</div>
<!-- @user:呼び出し先でuser情報を特定する !-->
<div class="col-md-8 offset-md-1" >
<h3>Books</h3>
<table class='table table-hover table-inverse'>
  <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  </tr>
  
  <% @books.each do |book| %>
  <tr>
    <td><%= link_to image_tag book.user.get_profile_image(100,100) %></td>
    <td><%= link_to book.title, book_path(book) %></td>
    <td><%= book.body %></td>
  </tr>
  <td>
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete do %>
    <i class="fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post do %>
    <i class="fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %> いいね
  <% end %>
<% end %>
</td>
  <% end %>

</table>
</div>
</div>
</div>